version: '3.7'

networks:
  vpc:

services:
  keycloak:
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    restart: unless-stopped
    networks:
      vpc:
        aliases:
          - keycloak
  setup:
    image: jboss/keycloak:latest
    entrypoint: /setup.sh
    depends_on:
      - keycloak
    volumes:
      - ./setup.sh:/setup.sh
    networks:
      vpc:
        aliases:
          - setup
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "26500:80"
    networks:
      vpc:
        aliases:
          - proxy
  zeebe:
    image: camunda/zeebe:${ZEEBE_VERSION:-latest}
    environment:
      - ZEEBE_LOG_LEVEL=${ZEEBE_LOG_LEVEL:-debug}
      - ZEEBE_BROKER_CLUSTER_NODEID=0
    networks:
      vpc:
        aliases:
          - zeebe
